### ISSUE TITLE
请问有ac68u机型的安装包吗？

### ISSUE THREAD

**Issue by Jackle910** [alalbb313/ss-trojan#1]

**Comment by alalbb313** [comment]
通用, 前提是固件版本>=384

**Comment by Jackle910** [comment]
@alalbb313 你的固件版本是多少的？我的最新的384.17提示我关键词非法，不让装了

**Comment by Jackle910** [comment]
我傻了，没看说明，搞定了

**Comment by ptyuyu** [comment]
> @alalbb313 你的固件版本是多少的？我的最新的384.17提示我关键词非法，不让装了

ac68u稳定吗？

**Comment by wwb306** [comment]
> 我傻了，没看说明，搞定了

68u的装了1.0.9的版本，Trojan能正常使用吗，我的国外链接怎么都连不上
